#!/bin/bash
#
#  Checks a Tecplot file generated by horses2plt.
#
#  Usage: ./check_tec.sh FILE.tec [ZONE_TYPE] [VARIABLE ...]
#
#     ZONE_TYPE: BRICK (volume FE), QUADRILATERAL (surface FE), ORDERED (multizone)
#                or "-" to skip the check.
#     VARIABLE:  variable names that must appear in the VARIABLES header.
#
#  horses2plt may exit with code 0 even if the conversion was not performed,
#  so the output file itself is what gets validated here.
#
file=$1
zone=${2:--}
shift 2 2>/dev/null

fail() { echo "FAILED [$file]: $*"; exit 1; }

[ -s "$file" ] || fail "file does not exist or is empty"

head -1 "$file" | grep -q '^TITLE' || fail "missing TITLE header"
varLine=$(grep -m1 '^VARIABLES' "$file") || fail "missing VARIABLES header"
grep -q '^ZONE' "$file" || fail "no ZONE found"

case $zone in
   -) ;;
   ORDERED) grep -m1 '^ZONE' "$file" | grep -q 'I=' || fail "expected ordered (multizone) zones" ;;
   *) grep -m1 '^ZONE' "$file" | grep -q "ET=$zone" || fail "expected ZONE with ET=$zone" ;;
esac

for var in "$@"; do
   echo "$varLine" | grep -q "\"$var\"" || fail "variable \"$var\" not found in: $varLine"
done

grep -qiE '(^|[^a-z])(nan|infinity)([^a-z]|$)' "$file" && fail "NaN/Infinity values found"

echo "OK [$file]: $(grep -c '^ZONE' "$file") zone(s), $varLine"
